# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f7efd9316f656fc6ea25dac2ed809849349723b040d3f947c574f7fe69da1f928c9ded825ac2be1768a81f24c4cad9ff59a485dcf9ec4f7111609b0a3e10ada

test:
  secret_key_base: 7ef043f1acb269aaa39ad8f8b2fd5f94cd5124d7ea76889c25c2e6408990c398ea34ac64a5294c4efc26dd43f6f0a9e834d81a64f0401be1732bbf31c8ea6959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
